import '../models/person.dart';
import '../models/family.dart';

/// Demo family for front-end only (no backend).
Family get demoFamily {
  final now = DateTime.now();
  return Family(
    father: Person(
      name: 'Ahmed',
      phone: '+33 6 12 34 56 78',
      dob: DateTime(1975, 5, 15),
      gender: 'Homme',
      bloodType: 'A',
      rhFactor: '+',
      height: 1.78,
      weight: 82,
      sugarLevel: 1.35,
      systolicBP: 142,
      diastolicBP: 88,
      heartRate: 78,
      allergies: ['Pénicilline', 'Pollen'],
      chronicDiseases: ['Hypertension', 'Diabète type 2'],
      vaccinesUpToDate: true,
    ),
    mother: Person(
      name: 'Samira',
      phone: '+33 6 98 76 54 32',
      dob: DateTime(1980, 8, 22),
      gender: 'Femme',
      bloodType: 'O',
      rhFactor: '-',
      height: 1.65,
      weight: 62,
      sugarLevel: 0.95,
      systolicBP: 118,
      diastolicBP: 76,
      heartRate: 72,
      allergies: ['Lactose'],
      chronicDiseases: [],
      vaccinesUpToDate: true,
    ),
    children: [
      Person(
        name: 'Youssef',
        phone: '',
        dob: DateTime(2015, 3, 10),
        gender: 'Garçon',
        bloodType: 'A',
        rhFactor: '+',
        height: 1.25,
        weight: 28,
        sugarLevel: 0.90,
        systolicBP: 95,
        diastolicBP: 60,
        heartRate: 85,
        allergies: ['Arachides'],
        chronicDiseases: [],
        vaccinesUpToDate: true,
      ),
      Person(
        name: 'Lina',
        phone: '',
        dob: DateTime(2018, 11, 5),
        gender: 'Fille',
        bloodType: 'O',
        rhFactor: '-',
        height: 1.05,
        weight: 18,
        sugarLevel: 0.88,
        systolicBP: 92,
        diastolicBP: 58,
        heartRate: 90,
        allergies: [],
        chronicDiseases: [],
        vaccinesUpToDate: false,
      ),
    ],
    familyHistory: ['Diabète type 2 (père)', 'Hypertension (grand-père)'],
  );
}
